FROM node:lts-alpine

WORKDIR /code

COPY package.json yarn.lock tsconfig.json ./

RUN npm i -g npm@latest

RUN npm upgrade -g yarn

RUN yarn install --force

COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]
